/**
 * Rich demo intelligence dataset for SocialPulse.
 * Perfectly matches backend schemas from api/main.py for full pipeline demonstration.
 */
export const DEMO_INTELLIGENCE_DATA = {
  status: "success",
  query: "Artificial Intelligence #AI",
  count: 8,
  circuit_breaker: {
    state: "CLOSED",
    failure_count: 0,
    threshold: 5,
    recovery_timeout: 300,
    remaining_cooldown: 0.0,
  },
  tweets: [
    {
      post_id: 1849204810294819201,
      user_id: 9481029481,
      text: "The new open-weights multimodal foundation models are genuinely outperforming proprietary APIs on reasoning benchmarks. Open source AI development is moving at lightspeed! 🚀🤖 #AI #OpenSource #Tech",
      created_at: new Date(Date.now() - 1000 * 60 * 14).toISOString(),
      lang: "en",
      like_count: 1420,
      retweet_count: 388,
      reply_count: 94,
      quote_count: 42,
      is_retweet: false,
      is_quote: false,
      is_reply: false,
      hashtags: ["AI", "OpenSource", "Tech"],
      mentions: [],
      user: {
        user_id: 9481029481,
        handle: "alex_deeptech",
        display_name: "Dr. Alex Vance",
        bio: "AI Systems Researcher @ Stanford. Building autonomous multi-agent swarms. Linux, open source advocate.",
        location_raw: "San Francisco, CA",
        followers_count: 84200,
        following_count: 612,
        verified: true,
      },
      sentiment: {
        label: "positive",
        score: 0.94,
        emotion: "admiration",
        emotion_score: 0.88,
        sarcasm_prob: 0.04,
        detected_language: "en",
        translated_text: null,
      },
      comments: [
        {
          post_id: 1849205120194819202,
          user_id: 8192840192,
          text: "Completely agree. Fine-tuning locally with LoRA on consumer GPUs is now viable for production workloads.",
          created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
          lang: "en",
          like_count: 142,
          retweet_count: 12,
          reply_count: 4,
          is_reply: true,
          in_reply_to_post_id: 1849204810294819201,
          user: {
            user_id: 8192840192,
            handle: "elena_gpu",
            display_name: "Elena Rostova",
            bio: "ML Engineer | CUDA kernel optimization | PyTorch",
            location_raw: "Zurich, Switzerland",
            followers_count: 12400,
            following_count: 340,
            verified: true,
          },
          sentiment: {
            label: "positive",
            score: 0.89,
            emotion: "agreement",
            emotion_score: 0.92,
            sarcasm_prob: 0.02,
          },
        },
        {
          post_id: 1849205340194819203,
          user_id: 7192840193,
          text: "Still worried about data provenance and uncurated web crawls in base pretraining corpora.",
          created_at: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
          lang: "en",
          like_count: 45,
          retweet_count: 3,
          reply_count: 1,
          is_reply: true,
          in_reply_to_post_id: 1849204810294819201,
          user: {
            user_id: 7192840193,
            handle: "cyber_ethicist",
            display_name: "Marcus Thorne",
            bio: "Digital rights researcher & policy scholar @ Oxford Internet Inst.",
            location_raw: "London, UK",
            followers_count: 28900,
            following_count: 512,
            verified: false,
          },
          sentiment: {
            label: "negative",
            score: 0.72,
            emotion: "worry",
            emotion_score: 0.79,
            sarcasm_prob: 0.08,
          },
        }
      ]
    },
    {
      post_id: 1849204910294819204,
      user_id: 6192840194,
      text: "Governments rolling out algorithmic compliance frameworks for frontier models without consulting real practitioners will only stifle independent startups.",
      created_at: new Date(Date.now() - 1000 * 60 * 28).toISOString(),
      lang: "en",
      like_count: 890,
      retweet_count: 215,
      reply_count: 73,
      quote_count: 19,
      is_retweet: false,
      is_quote: false,
      is_reply: false,
      hashtags: ["AIAct", "TechPolicy"],
      mentions: [],
      user: {
        user_id: 6192840194,
        handle: "priya_ai_founder",
        display_name: "Priya Sundaram",
        bio: "Founder & CTO @ NeuralCore. YC W23 alum. Angel investor in Indian deeptech startups.",
        location_raw: "Bengaluru, India",
        followers_count: 54100,
        following_count: 890,
        verified: true,
      },
      sentiment: {
        label: "negative",
        score: 0.81,
        emotion: "frustration",
        emotion_score: 0.84,
        sarcasm_prob: 0.12,
        detected_language: "en",
        translated_text: null,
      },
      comments: []
    },
    {
      post_id: 1849205010294819205,
      user_id: 5192840195,
      text: "The new robotic manipulation demonstration with vision-language-action policies is simply jaw-dropping. Zero-shot dexterous tool use in dynamic environments.",
      created_at: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
      lang: "en",
      like_count: 2310,
      retweet_count: 670,
      reply_count: 110,
      quote_count: 85,
      is_retweet: false,
      is_quote: false,
      is_reply: false,
      hashtags: ["Robotics", "VLA", "AI"],
      mentions: [],
      user: {
        user_id: 5192840195,
        handle: "kenji_robotics",
        display_name: "Kenji Sato",
        bio: "Robotics scientist @ RIKEN. Bipedal locomotion & neural representations.",
        location_raw: "Tokyo, Japan",
        followers_count: 41200,
        following_count: 420,
        verified: true,
      },
      sentiment: {
        label: "positive",
        score: 0.96,
        emotion: "excitement",
        emotion_score: 0.95,
        sarcasm_prob: 0.01,
        detected_language: "en",
        translated_text: null,
      },
      comments: []
    },
    {
      post_id: 1849205110294819206,
      user_id: 4192840196,
      text: "Oh fantastic, another corporate press release claiming AGI has been reached internally right before their venture round closes. How shockingly original.",
      created_at: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
      lang: "en",
      like_count: 3120,
      retweet_count: 480,
      reply_count: 142,
      quote_count: 64,
      is_retweet: false,
      is_quote: false,
      is_reply: false,
      hashtags: ["AGI", "VentureCapital"],
      mentions: [],
      user: {
        user_id: 4192840196,
        handle: "sarcastic_dev",
        display_name: "Dave K.",
        bio: "Senior Infrastructure Engineer. Breaking distributed systems since 2011.",
        location_raw: "Austin, TX",
        followers_count: 32000,
        following_count: 600,
        verified: false,
      },
      sentiment: {
        label: "negative",
        score: 0.88,
        emotion: "skepticism",
        emotion_score: 0.91,
        sarcasm_prob: 0.93,
        detected_language: "en",
        translated_text: null,
      },
      comments: []
    },
    {
      post_id: 1849205210294819207,
      user_id: 3192840197,
      text: "आर्टिफिशियल इंटेलिजेंस और मशीन लर्निंग से ग्रामीण स्वास्थ्य सेवाओं में बड़ा बदलाव आ रहा है। टेलीमेडिसिन डायग्नोस्टिक्स अब लाखों लोगों तक पहुंच रहा है।",
      created_at: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
      lang: "hi",
      like_count: 760,
      retweet_count: 182,
      reply_count: 31,
      quote_count: 12,
      is_retweet: false,
      is_quote: false,
      is_reply: false,
      hashtags: ["AIHealthcare", "DigitalIndia"],
      mentions: [],
      user: {
        user_id: 3192840197,
        handle: "dr_ananya_sharma",
        display_name: "Dr. Ananya Sharma",
        bio: "Physician & Digital Health Advocate. AI in radiology diagnostics.",
        location_raw: "New Delhi, India",
        followers_count: 19800,
        following_count: 410,
        verified: true,
      },
      sentiment: {
        label: "positive",
        score: 0.91,
        emotion: "optimism",
        emotion_score: 0.89,
        sarcasm_prob: 0.02,
        detected_language: "hi",
        translated_text: "Artificial Intelligence and Machine Learning are bringing massive transformation to rural healthcare. Telemedicine diagnostics is now reaching millions.",
      },
      comments: []
    }
  ],
  edges: [
    { source_user_id: 8192840192, target_user_id: 9481029481, edge_type: "reply", post_id: 1849205120194819202 },
    { source_user_id: 7192840193, target_user_id: 9481029481, edge_type: "reply", post_id: 1849205340194819203 },
    { source_user_id: 6192840194, target_user_id: 9481029481, edge_type: "mention", post_id: 1849204910294819204 },
    { source_user_id: 5192840195, target_user_id: 9481029481, edge_type: "retweet", post_id: 1849205010294819205 },
    { source_user_id: 4192840196, target_user_id: 6192840194, edge_type: "mention", post_id: 1849205110294819206 },
    { source_user_id: 3192840197, target_user_id: 6192840194, edge_type: "retweet", post_id: 1849205210294819207 },
  ],
  sentiment_summary: {
    total_analyzed: 5,
    sentiment_mix: {
      positive: { count: 3, percentage: 60.0 },
      negative: { count: 2, percentage: 40.0 },
      neutral: { count: 0, percentage: 0.0 },
    },
    emotion_mix: {
      admiration: { count: 1, percentage: 20.0 },
      excitement: { count: 1, percentage: 20.0 },
      optimism: { count: 1, percentage: 20.0 },
      skepticism: { count: 1, percentage: 20.0 },
      frustration: { count: 1, percentage: 20.0 },
    },
    avg_sarcasm_probability: 0.224,
  },
  demographics_summary: {
    total_users: 5,
    k_anonymity_threshold: 50,
    geo_distribution: {
      "<k50_suppressed": {
        count: 5,
        percentage: 100.0,
        note: "Cohorts below k=50 anonymity threshold are suppressed to protect privacy",
      },
    },
    language_distribution: {
      "<k50_suppressed": {
        count: 5,
        percentage: 100.0,
        note: "Cohorts below k=50 anonymity threshold are suppressed to protect privacy",
      },
    },
    profession_distribution: {
      "<k50_suppressed": {
        count: 5,
        percentage: 100.0,
        note: "Cohorts below k=50 anonymity threshold are suppressed to protect privacy",
      },
    },
    age_distribution: {
      "<k50_suppressed": {
        count: 5,
        percentage: 100.0,
        note: "Cohorts below k=50 anonymity threshold are suppressed to protect privacy",
      },
    },
  },
  trend_summary: {
    total_posts: 5,
    analyzed_window_hours: 24,
    rising_trends: [
      {
        keyword: "OpenSource AI",
        is_hashtag: false,
        volume: 342,
        growth_rate: 4.8,
        acceleration: 1.6,
        virality_score: 0.92,
        status: "viral_burst",
        reach: 184000,
      },
      {
        keyword: "#Robotics",
        is_hashtag: true,
        volume: 215,
        growth_rate: 3.2,
        acceleration: 0.9,
        virality_score: 0.81,
        status: "surging",
        reach: 98000,
      },
      {
        keyword: "#TechPolicy",
        is_hashtag: true,
        volume: 168,
        growth_rate: 2.7,
        acceleration: 0.5,
        virality_score: 0.74,
        status: "rising",
        reach: 72000,
      },
    ],
    predicted_viral_topics: [
      {
        keyword: "Multimodal Reasoning",
        is_hashtag: false,
        virality_score: 0.96,
        growth_rate: 5.4,
        status: "imminent_peak",
        volume: 480,
      },
      {
        keyword: "Local Fine-Tuning",
        is_hashtag: false,
        virality_score: 0.89,
        growth_rate: 3.8,
        status: "surging",
        volume: 310,
      },
    ],
    topic_clusters: [
      {
        topic_id: 1,
        label: "Open Source Foundation Models",
        top_terms: ["multimodal", "weights", "reasoning", "lora", "gpus"],
        volume: 4,
        growth_rate: 4.1,
        sentiment_distribution: { positive: 0.75, negative: 0.25 },
        sample_snippets: ["Open-weights multimodal foundation models outperforming proprietary APIs"],
      },
      {
        topic_id: 2,
        label: "AI Governance & Market Disruption",
        top_terms: ["policy", "compliance", "startups", "regulation"],
        volume: 3,
        growth_rate: 2.8,
        sentiment_distribution: { negative: 0.8, neutral: 0.2 },
        sample_snippets: ["Governments rolling out algorithmic compliance frameworks"],
      },
    ],
    chronological_shifts: ["Shift from prompt engineering toward sovereign small-models and autonomous tool-use."],
  },
  network_summary: {
    total_nodes: 16,
    total_edges: 22,
    graph_density: 0.18,
    nodes: [
      { id: "alex_deeptech", label: "Alex Vance", archetype: "authority", influence_score: 0.94, followers_count: 84200, pagerank: 0.082, in_degree: 5, community_id: 1, dominant_sentiment: "positive" },
      { id: "elena_gpu", label: "Elena Rostova", archetype: "amplifier", influence_score: 0.76, followers_count: 12400, pagerank: 0.045, in_degree: 3, community_id: 1, dominant_sentiment: "positive" },
      { id: "priya_ai_founder", label: "Priya Sundaram", archetype: "bridge", influence_score: 0.88, followers_count: 54100, pagerank: 0.071, in_degree: 4, community_id: 2, dominant_sentiment: "negative" },
      { id: "kenji_robotics", label: "Kenji Sato", archetype: "authority", influence_score: 0.85, followers_count: 41200, pagerank: 0.068, in_degree: 4, community_id: 3, dominant_sentiment: "positive" },
      { id: "sarcastic_dev", label: "Dave K.", archetype: "amplifier", influence_score: 0.69, followers_count: 32000, pagerank: 0.038, in_degree: 2, community_id: 2, dominant_sentiment: "negative" },
      { id: "dr_ananya_sharma", label: "Dr. Ananya Sharma", archetype: "bridge", influence_score: 0.79, followers_count: 19800, pagerank: 0.052, in_degree: 3, community_id: 3, dominant_sentiment: "positive" },
      { id: "marcus_thorne", label: "Marcus Thorne", archetype: "critic", influence_score: 0.72, followers_count: 28900, pagerank: 0.041, in_degree: 2, community_id: 2, dominant_sentiment: "negative" },
      { id: "node_alpha", label: "TechChronicle", archetype: "amplifier", influence_score: 0.65, followers_count: 110000, pagerank: 0.062, in_degree: 6, community_id: 1, dominant_sentiment: "neutral" },
      { id: "node_beta", label: "AI_Research_Hub", archetype: "authority", influence_score: 0.82, followers_count: 95000, pagerank: 0.074, in_degree: 5, community_id: 1, dominant_sentiment: "positive" },
      { id: "node_gamma", label: "QuantumLeap", archetype: "bridge", influence_score: 0.58, followers_count: 14000, pagerank: 0.031, in_degree: 2, community_id: 3, dominant_sentiment: "positive" },
      { id: "node_delta", label: "SiliconPolicy", archetype: "critic", influence_score: 0.63, followers_count: 22000, pagerank: 0.039, in_degree: 3, community_id: 2, dominant_sentiment: "negative" },
      { id: "node_epsilon", label: "DeepLearningWeekly", archetype: "amplifier", influence_score: 0.71, followers_count: 67000, pagerank: 0.058, in_degree: 4, community_id: 1, dominant_sentiment: "positive" },
    ],
    links: [
      { source: "elena_gpu", target: "alex_deeptech", edge_type: "reply", weight: 2 },
      { source: "marcus_thorne", target: "alex_deeptech", edge_type: "reply", weight: 1 },
      { source: "priya_ai_founder", target: "alex_deeptech", edge_type: "mention", weight: 3 },
      { source: "kenji_robotics", target: "alex_deeptech", edge_type: "retweet", weight: 2 },
      { source: "sarcastic_dev", target: "priya_ai_founder", edge_type: "mention", weight: 2 },
      { source: "dr_ananya_sharma", target: "priya_ai_founder", edge_type: "retweet", weight: 1 },
      { source: "node_alpha", target: "alex_deeptech", edge_type: "retweet", weight: 4 },
      { source: "node_beta", target: "alex_deeptech", edge_type: "quote", weight: 3 },
      { source: "node_gamma", target: "kenji_robotics", edge_type: "reply", weight: 2 },
      { source: "node_delta", target: "priya_ai_founder", edge_type: "mention", weight: 2 },
      { source: "node_epsilon", target: "elena_gpu", edge_type: "retweet", weight: 2 },
      { source: "node_beta", target: "elena_gpu", edge_type: "mention", weight: 1 },
      { source: "node_alpha", target: "kenji_robotics", edge_type: "retweet", weight: 2 },
      { source: "node_gamma", target: "dr_ananya_sharma", edge_type: "reply", weight: 2 },
    ],
    influencers: [
      {
        user_id: 9481029481,
        handle: "alex_deeptech",
        display_name: "Dr. Alex Vance",
        followers_count: 84200,
        influence_score: 0.94,
        archetype: "authority",
        pagerank: 0.082,
        in_degree: 5,
        out_degree: 1,
        betweenness: 0.28,
        community_id: 1,
        dominant_sentiment: "positive",
        verified: true,
      },
      {
        user_id: 6192840194,
        handle: "priya_ai_founder",
        display_name: "Priya Sundaram",
        followers_count: 54100,
        influence_score: 0.88,
        archetype: "bridge",
        pagerank: 0.071,
        in_degree: 4,
        out_degree: 2,
        betweenness: 0.35,
        community_id: 2,
        dominant_sentiment: "negative",
        verified: true,
      },
      {
        user_id: 5192840195,
        handle: "kenji_robotics",
        display_name: "Kenji Sato",
        followers_count: 41200,
        influence_score: 0.85,
        archetype: "authority",
        pagerank: 0.068,
        in_degree: 4,
        out_degree: 1,
        betweenness: 0.21,
        community_id: 3,
        dominant_sentiment: "positive",
        verified: true,
      },
      {
        user_id: 3192840197,
        handle: "dr_ananya_sharma",
        display_name: "Dr. Ananya Sharma",
        followers_count: 19800,
        influence_score: 0.79,
        archetype: "bridge",
        pagerank: 0.052,
        in_degree: 3,
        out_degree: 1,
        betweenness: 0.19,
        community_id: 3,
        dominant_sentiment: "positive",
        verified: true,
      },
    ],
    communities: [
      {
        community_id: 1,
        label: "Open Source ML Systems",
        color: "#ccff00",
        member_count: 6,
        top_influencers: ["@alex_deeptech", "@elena_gpu"],
        dominant_sentiment: "positive",
        sentiment_breakdown: { positive: 0.8, neutral: 0.2, negative: 0.0 },
      },
      {
        community_id: 2,
        label: "AI Policy & Startup Ecosystem",
        color: "#8b5cf6",
        member_count: 5,
        top_influencers: ["@priya_ai_founder", "@marcus_thorne"],
        dominant_sentiment: "negative",
        sentiment_breakdown: { positive: 0.1, neutral: 0.2, negative: 0.7 },
      },
      {
        community_id: 3,
        label: "Physical Embodiment & Applied Bio",
        color: "#06b6d4",
        member_count: 5,
        top_influencers: ["@kenji_robotics", "@dr_ananya_sharma"],
        dominant_sentiment: "positive",
        sentiment_breakdown: { positive: 0.9, neutral: 0.1, negative: 0.0 },
      },
    ],
    spread_cascade: [
      {
        step: 1,
        source: "alex_deeptech",
        target: "elena_gpu",
        edge_type: "reply",
        from_segment: "Community 1",
        to_segment: "Community 1",
        snippet: "Open-weights multimodal models outperforming proprietary APIs",
        sentiment: "positive",
        timestamp: "14m ago",
      },
      {
        step: 2,
        source: "elena_gpu",
        target: "priya_ai_founder",
        edge_type: "mention",
        from_segment: "Community 1",
        to_segment: "Community 2",
        snippet: "Local fine-tuning viable for production workloads",
        sentiment: "positive",
        timestamp: "10m ago",
      },
      {
        step: 3,
        source: "priya_ai_founder",
        target: "sarcastic_dev",
        edge_type: "quote",
        from_segment: "Community 2",
        to_segment: "Community 2",
        snippet: "Governments rolling out algorithmic compliance frameworks",
        sentiment: "negative",
        timestamp: "8m ago",
      },
    ],
  },
};
